<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 15 Jun 2013 22:41:05 -0300
 */

$conf['title'] = 'Chaudhry Docs';
$conf['template'] = 'drupal-garland-blue';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index';
$conf['tpl']['spacedok']['width'] = 'wide';
$conf['tpl']['spacedok']['sidebar_position'] = 'left';

// end auto-generated content
